- CHANGELOG.md
- src/cmd/tooth/init/init.go
- src/context/context.go
- go.mod creation when running `lip tooth init`.
None.
> Add bug fixes for v0.2.1

- CHANGELOG.md
- docs/en/creator_s_guide.md
- src/cmd/install/specifier.go
- src/cmd/install/utils.go
- src/cmd/tooth/init/init.go
- src/tooth/toothfile/toothfile.go
- src/tooth/toothfile/utils.go
- Failing to fetch tooth whose version has suffix `+incompatible`.
- Failing to parse wildcards.
None.
> Fix bugs for v0.2.1

- .github/workflows/build.yml
- src/context/context.go
- src/main.go
Add automatic versioning.
None.
> Add automatic versioning

- docs/en/commands/lip_uninstall.md
- docs/zh-Hans/commands/lip_uninstall.md
- docs/zh-Hans/tutorials/create_a_lip_tooth.md
> update ZH-Hans and add info

- .github/workflows/build.yml
- nsis/make_installer.nsi
> feat(build): nsis installer

- .github/workflows/build.yml
- docs/en/tooth_json_file_reference.md
- docs/zh-Hans/tooth_json_file_reference.md
- nsis/make_installer.nsi
Add multi-platform building.
None.
> build: add multi-platform building

- .github/workflows/build.yml
- nsis/make_installer.nsi
[feat(build): "Add to PATH" selection](https://github.com/LiteLDev/Lip/pull/15/commits/dbd534b80d699bacc480f2ce64bab3b46c636f13)
[fix(build): remaining folder](https://github.com/LiteLDev/Lip/pull/15/commits/83f8c1043e8de76e43868364efa78268a5346f76) 
[refactor(build): remove "Run Lip" button](https://github.com/LiteLDev/Lip/pull/15/commits/49cb349fc11553e8bd8ad55362da63313f6bf24f)
> build: some changes

- .github/workflows/build.yml
- nsis/make_installer.nsi
> build(release): add automatic release (#1)

- CHANGELOG.md
Add v0.3.4 to change log.
None.
> chores(changelog): add v0.3.4

- CHANGELOG.md
- docs/en/tooth_json_file_reference.md
- docs/zh-Hans/tooth_json_file_reference.md
Fix mistakes in documentation.
None.
> Fix mistakes in documentation

- README.md
- docs/assets/script.js
- docs/en/README.md
- docs/en/_coverpage.md
- docs/zh-Hans/README.md
- docs/zh-Hans/_coverpage.md
> docs(readme): optimize expression

- CHANGELOG.md
> chore(changelog): update changelog for v0.4.0

- CHANGELOG.md
- docs/en/_sidebar.md
- docs/en/commands/lip.md
- docs/en/commands/lip_exec.md
- docs/en/commands/lip_show.md
- docs/en/tutorials/create_a_tool.md
- docs/zh-Hans/_sidebar.md
- docs/zh-Hans/commands/lip_exec.md
- docs/zh-Hans/commands/lip_show.md
- docs/zh-Hans/tutorials/create_a_tool.md
- src/cmd/exec/exec.go
- src/cmd/install/install.go
- src/cmd/install/specifier.go
- src/cmd/install/utils.go
- src/cmd/lip.go
- src/cmd/show/show.go
- src/cmd/uninstall/utils.go
- src/main.go
Add features for v0.5.0
Fix #34 
Resolve #33 
Resolve #32 
> Add features for v0.5.0

- docs/en/commands/lip_exec.md
- docs/zh-Hans/_coverpage.md
- docs/zh-Hans/_sidebar.md
- docs/zh-Hans/commands/lip_exec.md
- docs/zh-Hans/commands/lip_show.md
- docs/zh-Hans/tooth_json_file_reference.md
- docs/zh-Hans/tutorials/create_a_tool.md
> Docs ：Translate new content

- CHANGELOG.md
- docs/en/tooth_json_file_reference.md
- docs/zh-Hans/tooth_json_file_reference.md
- src/cmd/install/install.go
- src/cmd/install/utils.go
- src/cmd/uninstall/utils.go
- src/tooth/toothmetadata/metadata.go
- src/tooth/toothrecord/record.go
Add per OS and platform placement support.
Resolve #36 
> Add per OS and platform placement support

- CHANGELOG.md
- docs/en/commands/lip_install.md
- docs/en/tooth_json_file_reference.md
- docs/zh-Hans/commands/lip_install.md
- docs/zh-Hans/tooth_json_file_reference.md
- src/cmd/install/install.go
- src/cmd/install/utils.go
- src/cmd/uninstall/utils.go
- src/tooth/toothmetadata/metadata.go
- src/utils/logger/logger.go
Allow installing system programs.
> Allow installing system programs

- CHANGELOG.md
- src/cmd/install/install.go
- src/main.go
Fix failing to update or remove Lip with Lip.
> Fix failing to update or remove Lip with Lip

- CHANGELOG.md
- docs/en/commands/lip.md
- docs/en/commands/lip_list.md
- docs/en/commands/lip_show.md
- docs/zh-Hans/commands/lip.md
- docs/zh-Hans/commands/lip_list.md
- docs/zh-Hans/commands/lip_show.md
- src/cmd/install/utils.go
- src/cmd/lip.go
- src/cmd/list/list.go
- src/cmd/show/show.go
- src/utils/logger/logger.go
> Release 0.10.0

- CHANGELOG.md
- src/cmd/list/list.go
> Release 0.11.4514

- docs/zh-Hans/README.md
- docs/zh-Hans/commands/lip.md
- docs/zh-Hans/commands/lip_exec.md
- docs/zh-Hans/commands/lip_install.md
- docs/zh-Hans/commands/lip_list.md
- docs/zh-Hans/commands/lip_show.md
- docs/zh-Hans/commands/lip_uninstall.md
- docs/zh-Hans/faq.md
- docs/zh-Hans/getting_started.md
- docs/zh-Hans/installation.md
- docs/zh-Hans/lipui_quickstart.md
- docs/zh-Hans/tooth_json_file_reference.md
- docs/zh-Hans/tutorials/submit_your_tooth_to_lip_registry.md
Translate new content and improve old content
> docs: update

- docs/zh-Hans/tooth_json_file_reference.md
- docs/zh-Hans/tutorials/submit_your_tooth_to_lip_registry.md
improve Chinese translation
typo and some untranslated parts
> docs: improve Chinese translation

- docs/zh-Hans/tutorials/create_a_lip_tooth.md
> chineseify

- docs/creator_quickstart.zh.md
- docs/faq.zh.md
- docs/index.zh.md
- docs/installation.zh.md
- docs/lipui_quickstart.zh.md
- docs/quickstart.zh.md
> Docs: Translate documents

- CHANGELOG.md
- README.md
- docs/commands/lip.md
- docs/commands/lip_cache.md
- docs/commands/lip_cache.zh.md
- docs/commands/lip_install.md
- docs/faq.md
- docs/faq.zh.md
- docs/index.en.md
- docs/index.zh.md
- docs/installation.md
- docs/installation.zh.md
- docs/lipui_quickstart.md
- docs/lipui_quickstart.zh.md
- docs/quickstart.md
- docs/quickstart.zh.md
- docs/tooth_json_file_reference.md
- docs/tutorials/create_a_lip_tooth.md
- internal/cmd/cmdlip/cmdlip.go
- internal/contexts/contexts.go
- mkdocs.yml
> refactor: rename Lip to lip

- cmd/lip/main.go
> fix: fix version number

- CHANGELOG.md
- cmd/lip/main.go
- internal/cmd/cmdlipinstall/cmdlipinstall.go
- internal/cmd/cmdlipuninstall/cmdlipuninstall.go
- internal/network/gomoduleproxy.go
- internal/tooth/archive.go
- internal/tooth/metadata.go
- Platform-specific items in tooth.json.
- Go module path escaping.
> Release 0.18.1

- docs/reference/tooth_json_file_reference.md
- docs/reference/tooth_json_file_reference.zh.md
- docs/tutorials/create_a_lip_tooth.md
- docs/tutorials/create_a_lip_tooth.zh.md
Add more Chinese translation.
Nope.
> docs: update Chinese translation

- .github/workflows/build.yml
Add missing build docs workflow
Nope
> ci: fix build docs workflow

- CHANGELOG.md
- docs/reference/lip.md
- docs/reference/lip.zh.md
- internal/cmd/cmdlip/cmdlip.go
> feat: add --no-color flag

- internal/path/path.go
> fix: fix .lip path in linux #129

- internal/install/install.go
- internal/tooth/archive.go
Fix lip unable to decompress .tar.gz
#140
> fix: fix unable to decompress .tar.gz #140

- internal/tooth/archive.go
Remove `println` which I have forgot to delete
No
> refactor: remove println for debug

- docs/index.zh.md
- docs/user-guide/faq.zh.md
- docs/user-guide/files/liprc-json.zh.md
- docs/user-guide/files/tooth-json.zh.md
- docs/user-guide/getting-started.zh.md
- docs/user-guide/installation.zh.md
> docs: Translate some content into Chinese

- Lip.Migration.Tests/MigrationFromV1Tests.cs
- Lip.Migration.Tests/MigratorFromV2Tests.cs
- Lip.Migration/MigratorFromV2.cs
Fixed multiple variants generated when migrate
> fix: fix migrate variants

- CHANGELOG.md
- Golang.Org.X.Mod/Semver.cs
- Lip.Core.Tests/LipConfigTests.cs
- Lip.Core.Tests/RuntimeConfigTests.cs
- Lip.Core/GoModuleArchiveFileSource.cs
- Lip.Core/Lip.Install.cs
- Lip.Core/RuntimeConfig.cs
- Lip.Migration.Tests/MigrationFromV1Tests.cs
- Lip.Migration/MigratorFromV2.cs
- docs/user-guide/files/liprc-json.md
- docs/user-guide/files/liprc-json.zh.md
- docs/user-guide/getting-started.md
- docs/user-guide/getting-started.zh.md
- Use goproxy.io as default go_module_proxies
- Fixed globbed platform when use lip migrate
- Removed useless platform property when manifest v2 doesn't have platforms property
- Fixed issue with +incompatible build metadata
> fix: fix some issues

- docs/user-guide/installation.md
- docs/user-guide/installation.zh.md
add download link for windows installer
> docs: add download link for windows installer
